const images = [
  '/assets/images/deportivo-quiro-2025-home-ecuador.webp',
  '/assets/images/emelec-2025-home-ecuador.webp',
  '/assets/images/españa-home-2025.webp',
  '/assets/images/fc-barcelona-1999-local-retro.webp',
  '/assets/images/fc-barcelona-2015-local-retro.webp',
  '/assets/images/ferrari-f1-team-2025.webp',
  '/assets/images/formula-1-norris.webp',
  '/assets/images/francia-2025-away.webp',
  '/assets/images/gorra-running-jersey-club.webp',
  '/assets/images/haas-f1-team-2025.webp',
  '/assets/images/idv-2025-home.webp',
  '/assets/images/inglaterra-2025-home.webp',
  '/assets/images/inter-miami-2025-local.webp',
  '/assets/images/inter-miami-home-2025.webp',
  '/assets/images/inter-milan-2025-home.webp',
  '/assets/images/japon-2025-home.webp',
  '/assets/images/juventus-2025-away.webp',
  '/assets/images/juventus-2026-local.webp',
  '/assets/images/leverkusen-2026-home.webp',
  '/assets/images/lewis-hamilton-ferrari-2025.webp',
  '/assets/images/liverpool-2026-local.webp',
  '/assets/images/liverpool-home-2025.webp',
  '/assets/images/liyon-2025-home.webp',
  '/assets/images/manchester-city-2025-away.webp',
  '/assets/images/manchester-city-2026-local.webp',
  '/assets/images/manchester-united-2007-local-retro.webp',
  '/assets/images/manchester-united-2011-tercera-retro.webp',
  '/assets/images/manchester-united-2025-away.webp',
  '/assets/images/manchester-united-2026-local.webp',
  '/assets/images/marseille-2025-home.webp',
  '/assets/images/max-verstappen-2025-special.webp',
  '/assets/images/mclared-f1-racing.webp',
  '/assets/images/monaco-2025-home.webp',
  '/assets/images/napoli-2025-away.webp',
  '/assets/images/polo-aston-martin-f1-team-2024.webp',
  '/assets/images/portugal-2004-local-retro.webp',
  '/assets/images/portugal-2025-home.webp',
  '/assets/images/psg-2025-tercera-.webp',
  '/assets/images/psg-2026-local.webp',
  '/assets/images/rb-f1-team-2025.webp',
  '/assets/images/real-betis-2025-home.webp',
  '/assets/images/real-madrid-2015-tercera-retro.webp',
  '/assets/images/real-madrid-2017-local-retro.webp',
  '/assets/images/real-madrid-2025-local.webp',
  '/assets/images/red-bull-racing-2025.webp',
  '/assets/images/roma-2025-home.webp',
  '/assets/images/sauber-f1-2025.webp',
  '/assets/images/williams-racing-2025.webp'
];

export const getRandomImage = () => {
  const randomIndex = Math.floor(Math.random() * images.length);
  return images[randomIndex];
};